name = "HC Blog"
license = "MIT"
licenselink = "https://5s9horizons.github.io/hc-blog/blob/master/LICENSE.md"
description = "A simple and clean blog theme for Hugo"
homepage = "https://5s9horizons.github.io/hc-blog/"
demosite = "https://5s9horizons.github.io/hc-blog/"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal",
  "light",
  "dark",
  "dark mode"
]
features = [
  "analytics",
  "favicon",
  "multilingual",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.124.0"

[author]
name = "Luiz F. A. de Prá"
homepage = "https://5s9horizons.github.io/hc-blog/"
